[build-system]
requires = ["setuptools >= 43.0.0", "wheel"]

[tool.codespell]
# Ref: https://github.com/codespell-project/codespell#using-a-config-file
skip = '.git,versioneer.py'
check-hidden = true
# ignore-regex = ''
# ignore-words-list = ''
