[tox]
envlist = lint,py3{10,11,12,13}
# These tests require git-annex which must be installed system-wide
skipsdist = false

[testenv]
changedir = __testhome__
extras = devel
commands =
    python -m pytest -c ../tox.ini {posargs:-s -v --cov=datalad_neuroimaging --pyargs datalad_neuroimaging}
passenv=
  HOME
  DATALAD_*
setenv=
# If need to flood with all the logs
# DATALAD_LOG_LEVEL=DEBUG

[testenv:lint]
skip_install = true
deps =
    codespell ~= 2.4.1
commands =
    codespell
