[tox]
envlist = lint,py3{10,11,12,13}
skipsdist = false

# -- To centralize reference to the project for easier reuse --
[_project]
name = datalad_neuroimaging

[testenv]
changedir = {tox_root}/__testhome__
extras = devel
commands =
    python -m pytest -c {tox_root}/tox.ini {posargs:-s -v --cov={[_project]name} --pyargs {[_project]name}}
passenv =
    HOME
    DATALAD_*
setenv =
# DATALAD_LOG_LEVEL = DEBUG

[testenv:lint]
changedir = {tox_root}
skip_install = true
deps =
    codespell ~= 2.4.1
commands =
    codespell
